### ISSUE TITLE
compatibility with nextjs 9.3

### ISSUE THREAD

**Issue by sandys** [jimmylee/next-postgres#1]
nextjs 9.3 replaces getinitialprops with getserversideprops or getstaticprops/getstaticpaths. 

would you consider updating to 9.3 ?

**Comment by jimmylee** [comment]
Yes

**Comment by sandys** [comment]
Thanks!

**Comment by jimmylee** [comment]
I've updated to 9.4 here: https://github.com/jimmylee/next-express-emotion

I'm going to re-evaluate the setup here. Thanks for bearing with me.

**Comment by sandys** [comment]
Thanks again!

**Comment by jimmylee** [comment]
We've updated to 10.0.2 so closing this issue since its stale.
