### ISSUE TITLE
Using with decoupled API?

### ISSUE THREAD

**Issue by jimmiejackson414** [jimmylee/next-postgres#11]
Hi there, wonderful library!

Apologies if this isn't a great place for this question, however I've pored over articles/SO/tutorials for awhile now and thought I'd give it a shot here!

I was wondering if you had any suggestions on implementing what you've created here with a decoupled API. In my repo I've got an 'api' folder which contains my Rails API for handling user authentication, but I know this library uses Express/Passport for user authentication. On my frontend I'm using Next.js and modeled my login after this repo.

Thank you!

**Comment by jimmiejackson414** [comment]
Thank you for your response, yes that's correct!

**Comment by jimmylee** [comment]
To get the development experience you want, the most beginner friendly & mainstream way is to use `docker` and `docker-compose`. In tandem they allow you to specify config for each of your services and run them simultaneously. 

You would need to add a few config files to your project, and become familiar with new commands. Here is a [medium post](https://medium.com/@fishpercolator/how-to-separate-frontend-backend-with-rails-api-nuxt-js-and-devise-jwt-cf7dd9da9d16) worth reading to get an idea of what you need to do.

This makes me think that it would be valuable to write a guide for running multiple services... If I end up getting some more spare time I may tackle this!

I hope this points you in the right direction. Good luck 🙏

**Comment by jimmiejackson414** [comment]
Sounds great! Docker is definitely one of those buzzwords I always hear about but have never really given a shot yet. Thanks for your time.
