### ISSUE TITLE
How to connect hosted postgres database secrets? 

### ISSUE THREAD

**Issue by dcsensor** [jimmylee/next-postgres#14]
Amazing repo, thank you for open sourcing. I am trying to connect the project with ElephantSQL's hosted postgres database, but I am unsure of what fields correspond with the fields you included in next-postgres' readme. 

Here's a screenshot of a test instance of ElephantSQL:

<img width="343" alt="Screen Shot 2019-03-19 at 10 53 05 AM" src="https://user-images.githubusercontent.com/48724757/54616643-536f4000-4a36-11e9-8ad3-e9afbec889a9.png">

In the example you provided, are all the fields required? So far, I have guessed the following pairings, but hasn't doesn't worked. 

```
now secrets add production-username   [User & default database]
now secrets add production-password   [Password]
now secrets add production-database   [Default database or server?]
now secrets add production-host       [Server or URL?]
now secrets add production-port       [Default to 5432?]
now secrets add production-secret     [API Key?]
```

Thanks for the help!

**Comment by jimmylee** [comment]
`production-host` -> `isilo.db.elephantsql.com`
`production-port` -> Default
`production-secret` -> Not the API key, this is for salting your passwords.
`production-database` -> `mfvskeiq`

**Comment by jimmylee** [comment]
Let me know if this doesn't work out, and I'll try myself using the service you're using.

Sorry about the delay here!

**Comment by dcsensor** [comment]
Hi Jimmy, thanks for replying. I can't seem to get it to work with this:

```
now secrets add production-username   mfvskeiq
now secrets add production-password   iuJ_tjRH5OgZ5hkP0Celd...
now secrets add production-database    mfvskeiq
now secrets add production-host            isilo.db.elephantsql.com
now secrets add production-port            5432
now secrets add production-secret         randomSalt
```

Would you mind trying it out with ElephantSQL and letting me know if you could get it working?

**Comment by jimmylee** [comment]
Double check your `add-production-database` name. Are you sure it's the same as the username? In the local config file of this project we use a name called `sampledb`, did you change it for your setup?

**Comment by jimmylee** [comment]
Closing this issue, feel free to open again after trying my suggestion! I hope you figure out what was causing the problem.
