### ISSUE TITLE
issue with bcrypt salt

### ISSUE THREAD

**Issue by sanderdebr** [jimmylee/next-postgres#2]
Hi,

I'm getting the following error from bcrypt:

Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue

Applies to this code:
```
const salt = BCrypt.genSaltSync(10);
const hash = BCrypt.hashSync(password, salt);
const double = BCrypt.hashSync(hash, salt);
const triple = BCrypt.hashSync(double, process.env.PASSWORD_SECRET);
```

I've generated my own password_secret with genSaltSync(10). Even with your secret I receive the same error.

The salt string is coming in correctly from .env file.

Without using the password_secret as salt it is working though. Is it better to add the password_secret?

Thanks for this great template btw, learning a lot from it.

**Comment by jimmylee** [comment]
@sanderdebr sorry it took so long to fix this. @jasonleyser was the one to find out what the problem was.

**Comment by jimmylee** [comment]
You just need to do a pull of the latest, we just needed to make the sure that `PASSWORD_SECRET` was initialized.
