### ISSUE TITLE
Suggestion on how to fetch data on a per page basis?

### ISSUE THREAD

**Issue by pruhstal** [jimmylee/next-postgres#2]
Hi @jimmylee,

I've been using this repo for about 3 months (since you first released it), and I've been able to fly pretty fast on a side project. So thank you so much for the nice starter kit.

One thing I noticed is that most of the data for all of the pages (comments, posts, etc.) comes from `getInitialStateData` from within https://github.com/jimmylee/next-postgres/blob/master/higher-order/withData.js#L9. While I can see why the reasoning behind it, it's not entirely optimal on sites that depend on a lot of data.

I'd like to get your thoughts on patterns to fetch data on a per-page basis that would be SEO friendly.

One solution I have for now is on a (logged in) page, say `privacy.js`: is within `componentWillMount` doing the fetch and then setting the state for the component based upon what comes back.

E.g.

```
  componentWillMount() {
    return this.props.dispatch(Actions.requestGetUserPrivacySettings({
      userId: this.props.viewer.id
    })).then((settings) => {
      this.setState(settings);
    });
  }
```

This works, but like I mentioned, I'd like to have something a bit more SEO friendly. I thought about maybe doing it in one of the controllers (within the route) kinda like this:

https://github.com/jimmylee/next-postgres/blob/master/index.js#L39

Where I'd just fetch the data and somehow pass it through to the component, but I'm stuck on how to do that.

Any ideas?

**Comment by jimmylee** [comment]
Hey thanks for writing in.

### Your instinct with getInitialProps is correct.

The way I had it, all my pages were fetching the same data, so I didn't need to have page specific `static getInitialProps`, it sounds like you might (completely reasonable), so here is an example of how to do that: 

```js
return class WithData extends Component {
   static async getInitialProps(ctx) {
      const props = {
        ...(await (ComposedComponent.getInitialProps
          ? ComposedComponent.getInitialProps(ctx, client, store)
          : {})),
      };

   const customGlobalStuff = {global: 'global stuff?'};

   return {
       ...customGlobalStuff,
       ...props 
   }

   render() {
       return <ComposedCompoennt {...this.props} >;
   }
}
```

Above is an example of how you can modify a higher order component, to have (1) global stuff you want to persist across all pages, and then (2) page specific stuff from the component it is wrapping.

### Yo Jim where do I get the page specific stuff then?

In a file such as `/pages/index.js` you can have a component that looks like:

```js
import React from 'react';
import Head from 'next/head';

export default class IndexPage extends React.Component {
    static async getInitialProps(ctx) {
        const response = await fetch('/dogs/where/they/at');
        const dogCount = await response.json();

        return {
            dogCount
        };
    }

    render() {
       return (
            <div>
                <Head>
                    <title>{this.props.dogCount} dogs</title>
                </Head>
                {this.props.dogCount}
            </div>
       );
    }
}
```

* Notice here we don't even need a higher order component, we can just return props.
* Here is an example of making a fetch request, but you don't even have to make a request if the data is just normal static data.
* So the purpose of using a higher order component is to centralize the data that flows into your application, just like you want to centralize the source of water and then trickle it down into the appropriate plants. 

I hope this helps you 😎 thanks for using the boilerplate, I need to bump it to `next 4.0.1`

**Comment by pruhstal** [comment]
@jimmylee thanks so much for the explanation! Definitely makes `withData.js` a bit more understandable (which I haven't really changed other than commenting out all the requests for anything other than `isAuthenticated` and `viewer`).

One thing I'm wondering is say that I want to use some of my initial "global stuff" in that fetch request from within my component. 

E.g. say a user is logged in and I'm accessing their user ID from `this.props.viewer.id`.

If I put this within my page component like:

```
  static async getInitialProps(ctx) {
    this.props.dispatch(Actions.requestGetUserPrivacySettings({
      userId: this.props.viewer.id
    })).then((settings) => {
      this.setState(settings);
    });
  }
```

`this.props` won't contain `dispatch` or `viewer` on the object, yet. 

Is there a way to have that global stuff available before I make that dispatch request?

This boilerplate is excellent -- great patterns to follow and really helped introduce me to Next. I plan on trying out expo once I master this :)

**Comment by jimmylee** [comment]
Everything you do within `getInitialProps` should be using the `ctx` argument. You should not be using `this.props` because you are within a [static class method](http://2ality.com/2015/02/es6-classes-final.html) (See static).

What you can do is in your withData you can modify `ComposedComponent.getInitialProps(ctx)` to take additional arguments, or add the store reference to `ctx` to `dispatch`

```
class MyPageClass extends React.Component {
    static async getInitialProps(ctx) {
         // assuming this is a fetch that takes arguments
         const response = await Actions.requestGetUserPrivacySettings({ 
             userId: ctx.req.parmas.userId 
         });
         const settings = await response.json();

         // assuming you figure out how to bind the right store reference to ctx.
         ctx.req._store.dispatch({ type: 'SAVE_SETTINGS', settings });

         return;
    }
 
    render() {
         console.log('now we have settings on first render based on how you set up your store in withData', this.props.settings);
         return(<div>Settings</div>);
    }
}
```

### If you don't need redux

Whatever settings that comes back from your promise, if you just want it for this page, can just be returned within `getInitialProps` and you don't have to use setState, and then in your `constructor` or your class you can set it to `this.state`

```
class MyPageClass extends React.Component {
    static async getInitialProps(ctx) {
         // assuming this is a fetch that takes arguments
         const response = await Actions.requestGetUserPrivacySettings({ 
             userId: ctx.req.parmas.userId 
         });
         const settings = await response.json();

         return {
              settings
         }
    }
 
    constructor(props) {
         super(props);

         this.state = {
              settings: settings
         }
    }

    render() {
         console.log('now we have settings on first render in just local state without redux', this.state.settings);
         return(<div>Settings</div>);
    }
}
```

**Comment by pruhstal** [comment]
Ok, wow. Just want to say thanks for being so informative and helpful. I'm learning a ton.

So I *think* I'm pretty close to figuring this out. At least, in my `getInitialProps` method, I'm now able to hit the db and get the actual settings.

That method looks like:

```
  static async getInitialProps(ctx) {
    const req = ctx.req;
    const store = req._store;
    const response = await store.dispatch(Actions.requestGetUserPrivacySettings({
      userId: req.user.dataValues.id
    }));
    const settings = await response.json();
    store.dispatch({type: 'SAVE_SETTINGS', settings});
    return;
  }
```

I'm using Redux because I'm basically just using your boilerplate still, so in `store.js` I've added a new case for `SAVE_SETTINGS` per your last comment above:

```
export const reducer = (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case 'UPDATE_STORE_KEYS':
      return mergeUpdatedKeys(action.data, state);
    case 'VIEWER_AUTHENTICATED':
      return mergeAuthState(action, state);
    case 'VIEWER_LOGOUT':
      return mergeLogoutState(state);
    case 'SAVE_SETTINGS':
    // action.settings contains the settings now
    default:
      return state;
  }
};
```

One thing I'm a little unclear on is what I should do with `action.settings` within `SAVE_SETTINGS`? Do I call one of the convenience methods like `mergeUpdatedKeys` with it so it gets attached to the state of my page component (`privacy.js`)?

FWIW, in `privacy.js`, I'm wrapped it with the HoC:

`export default withData({}, state => state)(SettingsPrivacy);`, although in other examples of your code I noticed you do this:

`export default connect(state => state)(CommentList);`

What's the benefit of wrapping one with the HoC vs just `connect`?

Thank you so so so much. Really appreciate it.

**Comment by pruhstal** [comment]
@jimmylee ok, think I finally figured this out!

In my page `privacy.js`

```
  static async getInitialProps(ctx) {
    const req = ctx.req;
    const store = req._store;
    const response = await store.dispatch(Actions.requestGetUserPrivacySettings({
      userId: req.user.dataValues.id
    }));
    const settings = await response.json();
    store.dispatch({type: 'SAVE_SETTINGS', settings});
    return store.getState();
  }
```

Then in my store:

```
export const reducer = (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case 'UPDATE_STORE_KEYS':
      return mergeUpdatedKeys(action.data, state);
    case 'VIEWER_AUTHENTICATED':
      return mergeAuthState(action, state);
    case 'VIEWER_LOGOUT':
      return mergeLogoutState(state);
    case 'SAVE_SETTINGS':
      return Object.assign({}, state, action.settings);
    default:
      return state;
  }
};
```

So now `settings` makes it back (and adds it to my store) such that I can reference `this.props.settings` and it's populated.

One thing that's weird is that on initial render of the page, I run into this:

![screen shot 2017-10-25 at 12 07 32 pm](https://user-images.githubusercontent.com/624807/32018036-731e6052-b97d-11e7-8643-f449e3b7ad67.png)

However, when I refresh, all is good. Could this be an issue with SSR and Next.js?

**Comment by pruhstal** [comment]
When I add in some debugging:

```
  static async getInitialProps({ req, query }) {
    const isServer = !!req
    console.log('getInitialProps called:', isServer ? 'server' : 'client')
}
```

that error above of `Cannot read property '_store' of undefined` is happening on the client.

Upon a second refresh, it grabs it from the server and renders everything properly. Is this a problem with next.js or with my code?

**Comment by jimmylee** [comment]
(1) It looks like you can use `!process.browser` to avoid the call being made on the client (where req doesn't exist)

(2) Here is another option that I had the opportunity to think about.

- I want to break down the problem into a smaller subset and see if this would work for you.
- This may involve moving some code around.
- I think this will provide a more clear blueprint of how this could come together.

Given a page.

```js
import React from 'react';
import Dogs from './Imaginary-Components';
import withData from './Imaginary-HOCS';

class Page extends React.Component {
    static async getInitialProps({ req }) {
        const response = await fetch('/someApiRequest');
        const dogs = await response.json();

        return { dogs }
    }

    render() {
      return (
        <Dogs />
      )
    }
}

export default withData()(Page);
```

Given a dog component

```js
import React from 'react';
import { connect } from 'redux';

const mapStateToProps(state => { dogs: state.dogs });

class Dogs extends React.Component {
  render() {
    return (
      <div>{this.props.dogs}</div>
    )
  }
}

export default connect(mapStateToProps)(Dogs);
```

- I feel like eveything up to here is familiar to you, Just your typical redux.
- Here is a variant of withData that will suit your needs, because I think you want to keep everything in your redux store based on your examples.

```js
export default () => ComposedComponent => {
  return class WithDataHigherOrder extends Component {
    static async getInitialProps(ctx) {
      let initialState = { ...options.state };

      // NOTE(jim):
      /*
        The Adjustment here is KEY.

        1. We pass ctx down
        2. No dispatch is required anymore, just return initialProps
        3. You can change the name of this function to `static getInitialState` instead if you need to use props still. And then put back the props code I took out.
      */
      if (ctx.req) {
        initialState = { ...initialState, ...(await ComposedComponent.getInitialProps(ctx)) };
      }

      const store = initializeReduxStore(ctx, initialState);

      return {
        store,
        initialState,
      };
    }

    render() {
      const { initialState, store } = this.props;

      const hasStore = store && store.dispatch && store.getState;
      const providerStore = hasStore
        ? this.props.store
        : initializeReduxStore({}, initialState);

      return (
        <Provider store={providerStore}>
          <ComposedComponent />
        </Provider>
      );
    }
  };
};
```

Let me know if this helps! Thanks for using this man, makes me think I need to rework the starting example to give better scaffolding at the start.
