### ISSUE TITLE
Change paths for textarea, moved under higher-order

### ISSUE THREAD

**Issue by arcalinea** [jimmylee/next-postgres#7]
In components directory, `CommentForm.js`, `CommentPreview.js`, `PostForm.js` 
and in pages directory, `pages/post.js` 
all had paths expecting `Textarea` to be under `components`, but it has been moved to the folder `higher-order`.

**Comment by jimmylee** [comment]
Thanks @arcalinea I'll address this asap :)

**Comment by jimmylee** [comment]
I just ran through the code and wasn't able to reproduce any issues with import paths being broken or files being in unexpected directories. One thing I could do is add `babel-plugin-module-resolver` to the example to remove any relative paths.

Could you show me a screenshot of the error message you're seeing?
